- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
    - name: Check if running in WSL
      shell: grep -qEi "(Microsoft|WSL)" /proc/version
      failed_when: false
      register: in_wsl
    - name: Whether use GitHub proxy
      set_fact:
        gh_proxy: ""
  tasks:
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/clash.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/im.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/r.yml
    - include_tasks: tasks/rust.yml
    - include_tasks: tasks/nerd-fonts.yml
    - include_tasks: tasks/tools.yml
    - include_tasks: tasks/fingerprint.yml
    - include_tasks: tasks/qemu.yml

- hosts: win10
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks: tasks/core-win.yml
    - include_tasks: tasks/tools-win.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/tweak-win.yml
