- name: Install basic system packages
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config"]

- name: Install system packages required for buiding neovim
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext", "clang", "autoconf", "automake", "doxygen"]

- name: Install other system packages
  become: true
  apt:
    name: ["curl", "wget", "htop", "python3-pip"]
