- name: Install basic system packages
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config"]

- name: Install missing firmware
  become: true
  when: in_wsl.rc != 0 and ansible_facts["distribution"] == "Debian"
  apt:
    name: ["firmware-misc-nonfree"]

- name: Install essential utility packages
  become: true
  when: in_wsl.rc != 0
  apt:
    name: ["feh", "rofi", "nitrogen", "lxpolkit", "unzip", "pulseaudio", "pavucontrol", "alacritty"]

- name: Install OpenSSH Server
  become: true
  apt:
    name: openssh-server

- name: Install system packages required for buiding neovim
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext", "clang", "autoconf", "automake", "doxygen"]

- name: Install other system packages
  become: true
  apt:
    name: ["curl", "wget", "htop", "python3-pip"]
