- name: Install basic system packages
  become: true
  when: ansible_facts["distribution"] != "Fedora"
  apt:
    name: ["build-essential", "cmake", "pkg-config"]

- name: Install missing firmware
  become: true

- name: Install OpenSSH Server
  become: true
  package:
    name: openssh-server

# for `Xephyr :5 & sleep 1 ; DISPLAY=:5 awesome`
- name: Install awesomewm
  become: true
  when: in_wsl.rc != 0
  block:
    - name: Install awesomewm on Debian-based
      when: ansible_facts["distribution"] != "Fedora"
      apt:
        name: ["awesome", "xserver-xephyr"]
    - name: Install awesomewm on Fedora
      when: ansible_facts["distribution"] == "Fedora"
      dnf:
        name: ["awesome", "xorg-x11-server-Xephyr"]

- name: Install system packages required for buiding neovim
  become: true
  block:
    - name: Install system packages required for buiding neovim on Debian-based
      when: ansible_facts["distribution"] != "Fedora"
      apt:
        name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext", "clang", "autoconf", "automake", "doxygen"]
    - name: Install system packages required for buiding neovim on Fedora
      when: ansible_facts["distribution"] == "Fedora"
      dnf:
        name: ["lua", "ninja-build", "libtool", "cmake", "gcc", "gcc-c++", "make", "pkgconfig", "unzip", "gettext", "curl"]

- name: Install essential utility packages
  become: true
  package:
    name: ["curl", "wget", "htop", "python3-pip", "rofi", "nitrogen", "lxpolkit", "unzip", "pipewire-pulseaudio", "pavucontrol", "alacritty"]
