- name: Install basic system packages
  become: true
  when: ansible_facts["distribution"] != "Fedora"
  apt:
    name: ["build-essential", "cmake", "pkg-config"]

- name: Install missing firmware
  become: true
  when: in_wsl.rc != 0
  block:
    - name: Install missing fireware for Debian
      when: ansible_facts["distribution"] == "Debian"
      apt:
        name: ["firmware-misc-nonfree"]
    - name: Install missing fireware for Fedora
      when: ansible_facts["distribution"] == "Fedora"
      dnf:
        name: ["iwlax2xx-firmware"]

- name: Install OpenSSH Server
  become: true
  package:
    name: openssh-server

- name: Install system packages required for buiding neovim
  become: true
  block:
    - name: Install system packages required for buiding neovim on Debian-based
      when: ansible_facts["distribution"] != "Fedora"
      apt:
        name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext", "clang", "autoconf", "automake", "doxygen"]
    - name: Install system packages required for buiding neovim on Fedora
      when: ansible_facts["distribution"] == "Fedora"
      dnf:
        name: ["lua", "ninja-build", "libtool", "cmake", "gcc", "gcc-c++", "make", "pkgconfig", "unzip", "gettext", "curl"]

- name: Install essential utility packages
  become: true
  package:
    name: ["curl", "wget", "htop", "python3-pip", "lxpolkit", "unzip", "pipewire-pulseaudio", "pavucontrol", "network-manager-applet", "blueman"]

- name: Install wezterm terminal emulator
  when: in_wsl.rc != 0
  block:
    - name: Check if wezterm is already installed
      shell: "command -v wezterm"
      register: wezterm_exists
      failed_when: no
    - name: Install wezterm if not installed
      become: true
      when: wezterm_exists.rc != 0
      block:
        - name: Install wezterm on Fedora
          when: ansible_facts["distribution"] == "Fedora"
          dnf:
            name: "{{ gh_proxy }}https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly-fedora37.rpm"
            disable_gpg_check: true
        - name: Install wezterm on Debian
          when: ansible_facts["distribution"] == "Debian"
          apt:
            deb: "{{ gh_proxy }}https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly.Debian11.deb"
        - name: Install wezterm on Ubuntu
          when: ansible_facts["distribution"] == "Ubuntu"
          apt:
            deb: "{{ gh_proxy }}https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly.Ubuntu22.04.deb"
