- name: Change Fedora to use the BFSU mirror
  when: ansible_facts["distribution"] == "Fedora"
  become: true
  block:
    - name: Backup original yum repos
      become: true
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: false
      loop:
      - src: "/etc/yum.repos.d/fedora.repo"
        dest: "/etc/yum.repos.d/fedora.repo.bak"
      - src: "/etc/yum.repos.d/fedora-modular.repo"
        dest: "/etc/yum.repos.d/fedora-modular.repo.bak"
      - src: "/etc/yum.repos.d/fedora-updates.repo"
        dest: "/etc/yum.repos.d/fedora-updates.repo.bak"
      - src: "/etc/yum.repos.d/fedora-updates-modular.repo"
        dest: "/etc/yum.repos.d/fedora-updates-modular.repo.bak"

    - name: Set the BFSU Fedora mirror
      block:
      - name: Comment out metalink for 'fedora' and 'fedora-modular' repos
        replace:
          path: "{{ item.path }}"
          regexp: "^metalink="
          replace: "#metalink="
        loop:
        - path: "/etc/yum.repos.d/fedora.repo"
        - path: "/etc/yum.repos.d/fedora-modular.repo"
      - name: Comment out metalink for 'fedora-updates' and 'fedora-modular-updates' repos
        replace:
          path: "{{ item.path }}"
          regexp: "^metalink="
          replace: "#metalink="
          before: "\\[updates.*-source\\]"
        loop:
        - path: "/etc/yum.repos.d/fedora.repo"
        - path: "/etc/yum.repos.d/fedora-modular.repo"

      - name: Enable BFSU mirror base URL for 'fedora' and 'fedora-modular' repos
        replace:
          path: "{{ item.path }}"
          regexp: "^#baseurl=http://download.example/pub/fedora/linux"
          replace: "baseurl=https://mirrors.bfsu.edu.cn/fedora"
        loop:
        - path: "/etc/yum.repos.d/fedora-updates.repo"
        - path: "/etc/yum.repos.d/fedora-updates-modular.repo"

      - name: Enable BFSU mirror base URL for 'fedora' and 'fedora-modular' repos
        replace:
          path: "{{ item.path }}"
          regexp: "^#baseurl=http://download.example/pub/fedora/linux"
          replace: "baseurl=https://mirrors.bfsu.edu.cn/fedora"
        loop:
        - path: "/etc/yum.repos.d/fedora.repo"
        - path: "/etc/yum.repos.d/fedora-modular.repo"
      - name: Enable BFSU mirror base URL for 'fedora-updates' and 'fedora-modular-updates' repos
        replace:
          path: "{{ item.path }}"
          regexp: "^#baseurl=http://download.example/pub/fedora/linux"
          replace: "baseurl=https://mirrors.bfsu.edu.cn/fedora"
          before: "\\[updates.*-source\\]"
        loop:
        - path: "/etc/yum.repos.d/fedora-updates.repo"
        - path: "/etc/yum.repos.d/fedora-updates-modular.repo"

    - name: Regerate dnf cache
      become: true
      dnf:
        state: "latest"
        update_cache: true

- name: Enable RPM Fusion repos
  when: ansible_facts["distribution"] == "Fedora"
  become: true
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
