- name: Install chezmoi and age
  when: ansible_facts['os_family'] != "Windows"
  block:
  - name: Check if chezmoi has already been installed
    stat:
      path: "{{ lookup('env', 'HOME') }}/.local/bin/chezmoi"
    register: chezmoi_stats

  - name: Install chezmoi
    when: chezmoi_stats.stat.exists == False
    block:
    - name: Get the latest release of chezmoi
      uri:
        url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
        return_content: true
      register: cm_latest
    - name: Install chezmoi
      unarchive:
        src: '{{ gh_proxy }}https://github.com/twpayne/chezmoi/releases/download/{{cm_latest.json.tag_name}}/chezmoi_{{cm_latest.json.tag_name[1:]}}_linux_amd64.tar.gz'
        remote_src: yes
        dest: "/tmp"
    - copy:
        src: "/tmp/chezmoi"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
        mode: "preserve"

  - name: Check if age has already been installed
    stat:
      path: "{{ lookup('env', 'HOME') }}/.local/bin/age"
    register: age_stats

  - name: Install age
    when: age_stats.stat.exists == False
    become: true
    block:
    - name: Get the latest release of age
      uri:
        url: https://api.github.com/repos/FiloSottile/age/releases/latest
        return_content: true
      register: age_latest
    - name: Install age
      unarchive:
        src: '{{ gh_proxy }}https://github.com/FiloSottile/age/releases/download/{{age_latest.json.tag_name}}/age-{{age_latest.json.tag_name}}-linux-amd64.tar.gz'
        remote_src: yes
        dest: "/tmp"
    - name: Copy age to '~/.local/bin'
      copy:
        src: "/tmp/age/age"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin"
        mode: "preserve"
    - name: Copy age-keygen to '~/.local/bin'
      copy:
        src: "/tmp/age/age-keygen"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin"
        mode: "preserve"

- name: Apply dot files
  when: ansible_facts['os_family'] != "Windows"
  shell: "chezmoi init --apply --force git@github.com:hongyuanjia/dotfiles.git"
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ lookup('env', 'PATH') }}"

- name: Apply dot files for Windows
  when: ansible_facts['os_family'] == "Windows"
  win_shell: "chezmoi init --apply --force https://github.com/hongyuanjia/dotfiles.git"
