- name: Check if there is a fingerprint reader
  shell: lsusb | grep "Fingerprint Reader" &> /dev/null
  failed_when: false
  register: has_fg

# ref: https://rcarrillo.dev/enable-fingerprint-scanner-on-pop-os-21-10/
- name: Enable fingerprint authorization
  when: in_wsl.rc != 0 and has_fg.rc == 0
  become: true
  block:
    - name: Install system packages for finger print authorization
      block:
        - when: ansible_facts["distribution"] != "Fedora"
          apt:
            name: ["fprintd", "libpam-fprintd"]
        - when: ansible_facts["distribution"] == "Fedora"
          dnf:
            name: ["fprintd-pam"]

    # next step: fprintd-enroll && sudo pam-auth-update
    - name: Enable fingerprint using PAM
      command: pam-auth-update --enable fprintd
