- name: Install Chinese input method
  when: in_wsl.rc != 0
  become: true
  block:
    - name: Install Chinese input method on Debian-based
      when: ansible_facts["distribution"] != "Fedora"
      apt:
        name: ["ibus-table-wubi"]
    - name: Install Chinese input method on Fedora
      when: ansible_facts["distribution"] == "Fedora"
      dnf:
        name: ["ibus-table-chinese-wubi-jidian"]
