- name: Ensure .fonts directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    state: directory

- name: Check if JetBrainsMono nerd fonts already exists
  shell: "ls {{ lookup('env', 'HOME') }}/.local/share/fonts/JetBrains*Mono*Nerd*Font*Complete*"
  register: jbnf_exists
  failed_when: no

- name: Install JetBrainsMono nerd fonts
  when: in_wsl.rc != 0 and jbnf_exists.rc != 0
  block:
    - name: Get the latest release of nerd fonts
      uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: nf_latest

    - name: Download JetBrainsMono nerd fonts
      unarchive:
        src: "{{ gh_proxy }}https://github.com/ryanoasis/nerd-fonts/releases/download/{{nf_latest.json.tag_name}}/JetBrainsMono.zip"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        remote_src: yes

    - name: Get Windows fonts to delete
      find:
        paths: "{{ lookup('env', 'HOME') }}/.local/share/fonts/"
        patterns: "*Windows Compatible*"
      register: win_fonts

    - name: Remove Windows fonts
      file:
        path: "{{ item['path'] }}"
        state: absent
      with_items: "{{ win_fonts['files'] }}"

    - name: Update font cache
      shell: fc-cache -fv
