- name: Check if Neovim is installed
  shell: "command -v nvim >/dev/null 2>&1"
  register: nvim_exists
  failed_when: no

- name: Install Neovim
  when: nvim_exists.rc != 0
  block:
  - name: Get packer.nvim
    git:
      repo: "https://github.com/wbthomason/packer.nvim"
      dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

  - name: Clone Neovim
    git:
      repo: "https://github.com/neovim/neovim.git"
      dest: "/tmp/neovim"

  - name: Build Neovim
    shell: "cd /tmp/neovim && make distclean && make -j 20"

  - name: Install Neovim
    shell: "cd /tmp/neovim && make install"
    become: true
