- name: Check if neovim is installed
  block:
    - name: Check if neovim exists
      shell: "command -v nvim"
      register: nvim_exists
      failed_when: no
    - name: Check neovim version
      when: nvim_exists.rc == 0
      shell: "nvim -v | head -1 | cut -d 'v' -f2 | cut -d '-' -f1"
      register: nvim_ver

- name: Install Neovim
  when: nvim_exists.rc != 0 or nvim_ver.stdout is version("0.8.3", "<", strict=True)
  block:
    - name: Clone Neovim
      git:
        repo: "{{ gh_proxy }}https://github.com/neovim/neovim.git"
        dest: "/tmp/neovim"

    - name: Build Neovim
      shell: "cd /tmp/neovim && make distclean && make CMAKE_BUILD_TYPE=Release -j 20"

    - name: Install Neovim
      shell: "cd /tmp/neovim && make install"
      become: true

    - name: Install xclip for system clipboard integration
      become: true
      apt:
        name: xclip
