- name: Check if Neovim is installed
  shell: "command -v nvim >/dev/null 2>&1"
  register: nvim_exists
  ignore_errors: yes
  failed_when: nvim_exists.rc != 0 and nvim_exists.rc != 127

- name: Get packer.nvim
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  when: nvim_exists is failed

- name: Clone Neovim
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "/tmp/neovim"
  when: nvim_exists is failed

- name: Build Neovim
  shell: "cd /tmp/neovim && make distclean && make -j 20"
  when: nvim_exists is failed

- name: Install Neovim
  shell: "cd /tmp/neovim && make install"
  become: true
  when: nvim_exists is failed
