# ref: https://christitus.com/vm-setup-in-linux/
- name: Install qemu/kvm and add config
  when: in_wsl.rc != 0
  become: true
  block:
  - name: Install system packages for qemu/kvm
    block:
    - when: ansible_facts["distribution"] != "Fedora"
      apt:
        name: ["qemu-kvm", "qemu-utils", "libvirt-daemon-system", "libvirt-clients", "virt-manager", "ovmf"]
    # currently, dnf module does not support passing options
    # see: https://github.com/ansible/ansible/issues/67187
    - when: ansible_facts["distribution"] == "Fedora"
      dnf:
        name: ["virt-install", "libvirt-daemon-config-network", "libvirt-daemon-kvm", "qemu-kvm", "virt-manager", "virt-viewer", "guestfs-tools", "libguestfs-tools", "python3-libguestfs", "virt-top"]

  - name: Check if the default network is started
    become: true
    shell: virsh net-list --all | grep default &> /dev/null
    failed_when: false
    register: network_started

  - name: Start default network for networking
    become: true
    when: network_started.rc != 0
    shell: virsh net-start default && sudo virsh net-autostart default

  - name: Add user to the required groups
    become: true
    block:
      - when: ansible_facts["distribution"] != "Fedora"
        user:
          name: "{{ lookup('env', 'USER') }}"
          groups: libvirt,libvirt-qemu,kvm,input,disk
          append: true
      - when: ansible_facts["distribution"] == "Fedora"
        user:
          name: "{{ lookup('env', 'USER') }}"
          groups: libvirt,qemu,kvm,input,disk
          append: true
