- name: Check if cargo is installed
  shell: "command -v cargo >/dev/null 2>&1"
  register: cargo_exists
  failed_when: no

- name: Install Rust
  when: cargo_exists.rc != 0
  block:
    - name: Check if running in WSL
      command: 'grep -qEi "(Microsoft|WSL)" /proc/version'
      failed_when: no
      register: in_wsl

    - when: in_wsl.rc !=0
      block:
        - name: Download Rustup installer
          get_url:
            url: https://sh.rustup.rs
            dest: /tmp/rust-init.sh
            mode: '0755'
            force: yes

        - name: Install Rustup
          command: /tmp/rust-init.sh -y

    - when: in_wsl.rc ==0
      block:
        - name: Download Rustup installer for WSL2
          when: in_wsl.rc == 0
          get_url:
            url: https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
            dest: /tmp/rustup-init
            mode: '0755'
            force: yes

        - name: Install Rustup
          command: /tmp/rustup-init -y
