- name: Install SSH on Linux
  when: ansible_facts['os_family'] != "Windows"
  block:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory

    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600

    - name: Install ssh key public
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644

    - name: Change ansible repo remote to SSH
      block:
        - name: Get current remotes
          failed_when: false
          shell: git remote -v
          args:
            chdir: "{{ playbook_dir }}"
          register: remotes

        - name: Test if it is using https
          failed_when: false
          shell: 'cat {{ remotes.stdout }} | grep "origin.*https" &> /dev/null'
          args:
            chdir: "{{ playbook_dir }}"
          register: http_remote

        - name: Change to SSH remote
          when: remotes.stdout == "" or http_remote.rc == 0
          block:
            - name: Remove HTTPS remote
              when: http_remote.rc == 0
              shell: git remote remove origin
              args:
                chdir: "{{ playbook_dir }}"

            - name: Add SSH remote
              shell: "git remote add origin git@github.com:hongyuanjia/ansible.git"
              args:
                chdir: "{{ playbook_dir }}"

- name: Install SSH on Windows
  when: ansible_facts['os_family'] == "Windows"
  block:
    - name: Ensure .ssh directory exists
      win_file:
        path: "{{ dest_key }}"
        state: directory

    - name: Install ssh key
      win_copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"

    - name: Install ssh key public
      win_copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
