- name: Install SSH on Linux
  when: ansible_facts['os_family'] != "Windows"
  block:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory

    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600

    - name: Install ssh key public
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644

    - name: Change ansible repo remote to SSH
      when: false
      block:
        - name: Test if it is using https
          shell: git remote -v | grep "origin.*https" &> /dev/null
          failed_when: false
          register: http_remote

        - name: Change to SSH remote
          when: http_remote.rc == 0
          block:
            - name: Remove HTTPS remote
              shell: git remote remove origin

            - name: Add SSH remote
              shell: "git remote add git@github.com:hongyuanjia/ansible.git"

- name: Install SSH on Windows
  when: ansible_facts['os_family'] == "Windows"
  block:
    - name: Ensure .ssh directory exists
      win_file:
        path: "{{ dest_key }}"
        state: directory

    - name: Install ssh key
      win_copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"

    - name: Install ssh key public
      win_copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
