- name: Install productivity packages
  become: true
  when: in_wsl.rc != 0
  package:
    name: ["bat", "tmux", "fzf", "ripgrep", "rofi", "unzip", "rofi", "gparted"]

- name: Install utility packages
  when: in_wsl.rc != 0
  become: true
  package:
    name: ["neofetch", "flameshot", "lxappearance", "gimp", "firefox", "feh", "zathura", "nitrogen"]

- name: Install Delta
  include_tasks: ./tasks/tools/delta.yml

- name: Install Starship
  include_tasks: ./tasks/tools/starship.yml

- name: Install TinyTex
  include_tasks: ./tasks/tools/tinytex.yml

- name: Install LazyGit
  include_tasks: ./tasks/tools/lazygit.yml

- name: Install wslu
  include_tasks: ./tasks/tools/doublecmd.yml

- name: Install wslu
  include_tasks: ./tasks/tools/wslu.yml
