- name: Install productivity packages
  become: true
  apt:
    name: ["bat", "tmux", "fzf", "ripgrep", "rofi", "unzip"]

- name: Install utility packages
  become: true
  apt:
    name: ["neofetch", "flameshot", "lxappearance", "gimp", "firefox"]

- name: Install Delta
  include_tasks: ./tasks/tools/delta.yml

- name: Install Starship
  include_tasks: ./tasks/tools/starship.yml

- name: Install TinyTex
  include_tasks: ./tasks/tools/tinytex.yml

- name: Install LazyGit
  include_tasks: ./tasks/tools/lazygit.yml

- name: Install wslu
  include_tasks: ./tasks/tools/wslu.yml
