- name: Tweak Windows 10 behavior
  block:
    - name: Disable UAC notification
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: ConsentPromptBehaviorAdmin
        data: 0
        type: dword
