- name: Install Zsh
  become: true
  package:
    name: ["zsh"]

- name: Install chsh on Fedora
  when: ansible_facts["distribution"] == "Fedora"
  become: true
  dnf:
    name: "util-linux-user"
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true

- name: Check if Oh-My-Zsh has already been installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh

- name: Install Oh-My-Zsh
  when: oh_my_zsh.stat.exists == False
  block:
    - name: Install Oh-My-Zsh
      shell: sh -c "$(curl -fsSL {{ gh_proxy }}https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install zsh-autosuggestions
  git:
    repo: "{{ gh_proxy }}https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
