- name: Install Zsh
  apt:
    name: ["zsh"]
  become: true

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true

- name: Check if Oh-My-Zsh has already been installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh

- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh.stat.exists == False

- name: Install zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
