- name: Check if TinyTeX has already been installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.TinyTeX"
  register: tinytex

- name: Install TinyTeX
  when: tinytex.stat.exists == False
  block:
  - name: Download TinyTeX installer
    get_url:
      url: https://yihui.org/tinytex/install-bin-unix.sh
      dest: /tmp/install-bin-unix.sh
      mode: '0755'
      force: yes

  - name: Install TinyTex
    shell: /tmp/install-bin-unix.sh
